# Generated by Django 5.2.8 on 2025-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('milk', 'Milk'), ('chocolate', 'Chocolate'), ('masala', 'Masala'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('bakery', 'Bakery'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
