# Generated by Django 5.2.8 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(max_length=15)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('rider_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('rider_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('payment_status', models.CharField(default='Unpaid', max_length=50)),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('reason_for_return', models.TextField()),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('refund_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='stock_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('weight', models.FloatField(max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
