# Generated by Django 5.2.8 on 2025-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
