# Generated by Django 5.2.8 on 2025-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_storesales_delete_attendance_delete_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesales',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
