# Generated by Django 5.2.8 on 2025-11-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='store_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
