# Generated by Django 5.2.8 on 2025-11-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='firings',
            new_name='Firing',
        ),
        migrations.RenameModel(
            old_name='hiring_requests',
            new_name='HiringRequest',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.RenameModel(
            old_name='vendor_registeration',
            new_name='VendorRegistration',
        ),
    ]
